Travis -> GitHub Actions Conversion
CruGlobal/campus-contacts-web pull request #867
Opened 2023-01-30 21:11 UTC by j2trumpet

2023-01-30 21:12 UTC, wrandall22 commented
You'll need to delete the travis file, and should squash all these commits together.

2023-01-30 21:13 UTC, wrandall22 commented on .github/workflows/node.js.yml
> +                  args: -s https://codecov.io/bash
Looks like this is [deprecated](https://docs.codecov.com/docs/about-the-codecov-bash-uploader)

2023-01-30 22:14 UTC, j2trumpet commented on .github/workflows/node.js.yml
> +                  args: -s https://codecov.io/bash
I've swapped this out for the [official codecov action](https://github.com/marketplace/actions/codecov). The action passes, though it says it didn't find any coverage files. There weren't any files specified in the travis script and I can't see if there was anything specified in travis itself.

2023-01-31 14:00 UTC, dr-bizz requested changes
Great job. I see a few tweaks but not much.

2023-01-31 15:41 UTC, j2trumpet commented on .github/workflows/node.js.yml
> +            - travis-gha-conversion
@dr-bizz So I should target both `master` and `staging`? The Travis file is identical between the two branches.

2023-01-31 15:43 UTC, j2trumpet commented on .github/workflows/node.js.yml
> +    workflow_dispatch:
@dr-bizz If I understand `workflow_dispatch` correctly (and it's possible I don't), it allows us to run the workflow manually - no push required. If something happened on OneSky and we needed to reupload the `en-US.js` file, this ability could come in handy.

2023-01-31 16:17 UTC, dr-bizz commented on .github/workflows/node.js.yml
> +    workflow_dispatch:
No, you're correct. I didn't understand what `workflow_dispatch `did, so I assumed it needed some options/inputs for it to run.
Looking through the documentation, I see that you have configured it correctly and the options/inputs are optional. - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

2023-01-31 16:35 UTC, dr-bizz commented on .github/workflows/node.js.yml
> +            - travis-gha-conversion
Yes, I believe so. You'll need to configure `push` to have both `master` and `staging` branches and `pull_request` only to have the `master` branch since I don't believe devs do PRs to staging on this repo.

I am a little confused by the travis.yml file. It doesn't mention any branches, so I assume that means Travis CI runs on all branches? https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches
If that is the case, you'll need to do something like this:
```
on:
  push:
    branches:    
      - '**'
```
Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

2023-01-31 17:29 UTC, j2trumpet commented on .github/workflows/node.js.yml
> +            - travis-gha-conversion
@dr-bizz I believe this syntax works for targeting every `push` regardless of branch.
```
on:
  push:
  pull_request: ...
```
However, I've noticed since I first added any mention of branches other than my feature branch to `push` and `pull_request` this morning that the script is getting triggered twice and I can't figure out why. `pull_request` should only be firing on `master`.

2023-01-31 17:56 UTC, j2trumpet commented on .github/workflows/node.js.yml
> +                  args: -s https://codecov.io/bash
@wrandall22 Does my update look good?

2023-01-31 17:57 UTC, dr-bizz commented on .github/workflows/node.js.yml
> +            - travis-gha-conversion
I think because you're pushing to your branch, it triggers the `pull` and then because you're on a PR merging into master, you also trigger the `pull_request`.

2023-02-01 14:41 UTC, dr-bizz commented on .github/workflows/node.js.yml
> +        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/travis-gha-conversion'
```suggestion
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
```

2023-02-01 14:42 UTC, dr-bizz commented on .github/workflows/node.js.yml
> +        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/travis-gha-conversion'
I'm guessing you left this here so you can test it, but just wanted to double check.

2023-02-01 16:00 UTC, j2trumpet commented on .github/workflows/node.js.yml
> +        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/travis-gha-conversion'
@dr-bizz Yes, that needs to be done, but I'm waiting to do it until it's the only thing that needs doing so that I can continue to make sure this upload is working with any other changes I make. Is this the only thing left to do before you'll approve it?

2023-02-01 16:06 UTC, j2trumpet commented on .github/workflows/node.js.yml
> +            - travis-gha-conversion
@dr-bizz Didn't you explain that above? Because I'm pushing to a branch that has an active PR, it's triggering `pull_request` in addition to `push`?

2023-02-01 18:09 UTC, j2trumpet commented on .github/workflows/node.js.yml
> +            - travis-gha-conversion
@dr-bizz I think I may have had a syntax error, though I would have expected GHA to fail if that were the case. It's only running only once now. When I first pushed the syntax change, it ran twice, but it's run only once on the two pushes since then.

2023-02-01 19:23 UTC, dr-bizz commented on .github/workflows/node.js.yml
> +            - travis-gha-conversion
Brilliant!

2023-02-01 19:28 UTC, dr-bizz commented
@j2trumpet, code looks good to me! AWS Amplify is failing; upon investigating, the server worked when the pull_request branches were set to `travis-gha-conversion` instead of `- master`.

2023-02-01 20:23 UTC, wrandall22 commented on .github/workflows/node.js.yml
> +                  args: -s https://codecov.io/bash
You may need to pass in the token, not sure. I saw someone do that recently.

2023-02-13 16:28 UTC, wrandall22 approved these changes

2023-02-14 18:04 UTC, j2trumpet commented on .github/workflows/node.js.yml
> +                  args: -s https://codecov.io/bash
@wrandall22 The [documentation](https://github.com/marketplace/actions/codecov#usage) says a token isn't required for public repos and this one is public.

2023-02-15 00:16 UTC, j2trumpet commented
@wrandall22 I've removed the Travis file, but the PR is still looking for it. I see a [webhook](https://github.com/CruGlobal/campus-contacts-web/settings/hooks) pointing to `https://notify.travis-ci.org/` and Travis CI listed in the repo's [app integrations](https://github.com/CruGlobal/campus-contacts-web/settings/installations) (though I can't configure it). What do I need to do to fully remove Travis?

2023-02-15 13:34 UTC, wrandall22 commented
It is on the branch protection settings for the `master` branch.

2023-02-20 17:58 UTC, j2trumpet commented
@wrandall22 So am I clear to get rid of that protection setting?

2023-02-20 18:06 UTC, wrandall22 commented
Yes, specifically the one saying that Travis needs to succeed (not the whole branch protection).

2023-02-20 18:29 UTC, j2trumpet commented
@dr-bizz Have I made the changes you requested? If so, can you mark your suggestion as completed?

2023-02-20 19:13 UTC, dr-bizz approved these changes

2023-02-20 19:24 UTC, merged

2023-02-20 19:26 UTC, wrandall22 commented on .github/workflows/node.js.yml
> +        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/travis-gha-conversion'
@j2trumpet you forgot to update this before merge.

2023-02-20 19:52 UTC, wrandall22 commented on .github/workflows/node.js.yml
> +        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/travis-gha-conversion'
You need a new PR